import type { CharDef } from './types';

/** 三峰瑠衣(応援)のタイミング。物理・AI・描画で同じ値を使う。単位は60fpsのフレーム。 */
export const CHEER = {
  secondClap: 9,
  turnPivot: 16,
  echoTurn: 24,
  echoReturnSpeed: 3.8,
  echoDrop: 16,
  waveSpeed: 8,
  waveLife: 52,
  rallyFrames: 180,
  rallySpeed: 1.15,
  airCeiling: 64,
} as const;

/**
 * motoneta1.md「三年生編 一学期／第四章 球技大会、二点差」の体育着アレンジ。
 * 原文は紺のネクタイ。体育着・鉢巻は mitsumine_taiiku.jpg と今回の指定による。
 * 制服版の猫／作戦ノート／掴み超必殺は流用しない。
 */
export const MITSUMINE_CHEER: CharDef = {
  id: 'mitsumine_cheer',
  hidden: true,
  name: '三峰瑠衣(応援)',
  kana: 'みつみね・るい（おうえん）',
  title: '理数科側の、素直じゃない声援',
  affiliation: '内進コース／球技大会・理数科応援席',
  tie: '紺（今日は着用せず）',
  tieColor: '#29334e',
  outfitLabel: '体育着・白い鉢巻',
  color: '#fb7185',
  light: '#fff1f2',
  hp: 90,
  speed: 2.55,
  jump: 6.5,
  dmgMul: 1,
  look: {
    hair: 'bob',
    hairColor: '#50372f',
    hairDark: '#302626',
    skin: '#f5d3c7',
    skinDark: '#dca99b',
    eyeColor: '#694536',
    gender: 'f',
    outfit: 'gym',
    weapon: 'none',
    winPose: 'tsundere',
  },
  airControl: { speed: 2.9, acceleration: 0.7, liftFrames: 28 },
  passive: {
    name: 'アリーナ・ステップ',
    desc: '最速の地上移動。空中でも左右で加速・反転、離すとブレーキ。上でAIRを使って浮き直し、下で急降下。空中弱・強は各1回、着地で再使用可。空中ガードはできない。',
  },
  moves: {
    light: {
      key: 'light',
      name: '裏拍クラップ',
      desc: '「べ、別に」の間にパン、パンと二拍。時間差の2ヒットで足を止める短い拍手。拳ではなく、両手の音で届かせる。',
      callout: ['べ、別に！', 'よそ見しない！', 'ちゃんと見てるから！'],
      startup: 3,
      active: 8,
      recovery: 9,
      dmg: 3,
      hitstun: 15,
      kbx: 0.8,
      kby: 0,
      box: { x: 2, y: -36, w: 23, h: 18 },
      kind: 'melee',
      pose: 'cheerClap',
      sfx: 'clap',
    },
    heavy: {
      key: 'heavy',
      name: 'サイドライン・折り返し',
      desc: '一歩引くフェイント→相手をすり抜ける全力ステップ→振り返って急停止の一撃。攻撃判定は折り返しだけ。近くなら背後を取れるが、止まった後は隙が大きい。',
      callout: ['こっち、空いてる！', '見に来ただけだってば！', '追いつけるでしょ？'],
      startup: 8,
      active: 10,
      recovery: 19,
      dmg: 11,
      hitstun: 25,
      kbx: 2.5,
      kby: 4.2,
      knockdown: true,
      box: { x: 0, y: -31, w: 25, h: 27 },
      moveX: 4.8,
      kind: 'melee',
      pose: 'cheerTurn',
      sfx: 'squeak',
    },
    special: {
      key: 'special',
      name: '二階席エコー・聞こえてる？',
      desc: '前へ声を飛ばし、少し先で反響して低い位置から戻す往復弾。行きと帰りで各1ヒット。自分も走り込んで挟み込める。設置は1つまで、空中では出せない。',
      callout: ['聞こえてるでしょ！', '三重、前、空いてる！', '返事くらいしなさいよ！'],
      startup: 12,
      active: 1,
      recovery: 19,
      dmg: 7,
      hitstun: 19,
      kbx: 1.3,
      kby: 0,
      kind: 'projectile',
      pose: 'cheerCall',
      sfx: 'cheer',
      projectile: { kind: 'cheerEcho', vx: 3.4, life: 68, w: 16, h: 15 },
      cooldown: 24,
    },
  },
  airMoves: {
    light: {
      key: 'light',
      name: '見てるだけ！・空中手拍子',
      desc: '斜め下に拍手の音を飛ばし、反動でふわっと浮き直す。空中でも方向転換可能。1ジャンプ1回なので連打で飛び続けることはできない。',
      callout: ['べ、別に見てない！', '上からなら見えるし！', 'そこ、フリー！'],
      startup: 4,
      active: 1,
      recovery: 10,
      dmg: 6,
      hitstun: 17,
      kbx: 1.4,
      kby: 0,
      kind: 'projectile',
      pose: 'airClap',
      sfx: 'clap',
      projectile: { kind: 'cheerNote', vx: 2.8, vy: 2.2, life: 38, w: 13, h: 11 },
    },
    heavy: {
      key: 'heavy',
      name: '一階まで、一直線！',
      desc: '二階席から駆け下りる勢いで急降下。直撃した時だけ跳ね返って空へ戻る。ガード・空振りでは跳ねず、着地硬直あり。跳ね返ってもAIRと技回数は回復しない。',
      callout: ['降りてきただけ！', '話、まだ終わってない！', '三重、待ちなさいよ！'],
      startup: 5,
      active: 24,
      recovery: 18,
      dmg: 12,
      hitstun: 26,
      kbx: 2,
      kby: 3.8,
      knockdown: true,
      box: { x: -5, y: -19, w: 21, h: 25 },
      kind: 'melee',
      pose: 'airDive',
      sfx: 'squeak',
    },
  },
  superName: '残り三十秒・声が枯れるまで',
  superQuote: '三重、いっけぇーーっ！！',
  superDesc: '両手を口に添えて、三段階の大声援！ 音の輪が順に広がり、届いた敵に6→6→18ダメージ（ガード可）。声が通った場所の敵弾をかき消す。最後の声で自分と生存中の味方が3秒間スピードアップ。二点差でも、応援は取り消さない。',
  intro: 'べ、別に。こっちの方が面白いから！',
  wins: ['応援に来ただけ。……本当だから！', '勝ったなら、素直に喜びなさいよ', '声、大きかった？ ……忘れて！', 'あんたが全力なら、あたしだって……何でもない！'],
  matchupWins: {
    mie: ['あんたのプレー、かっこよかった。……二回は言わない！', '冷笑してなかった。全力だった。……ちゃんと、見てたよ'],
    ryoma: ['最後、三重があんたにパスした意味、忘れないでよ', '外したって、全力だったのは見てた。……次は入れなさいよ'],
    naito: ['三重ばっかり見てた？ ……蘭、声が大きい！'],
    mitsumine: ['人には素直にって言えるのにね。……何よ、その顔！'],
    terachi: ['今の応援、切り抜き禁止！ 絶対だからね！'],
    rei: ['確実なパスじゃなかった。でも、あれが三重の選んだプレーでしょ'],
    sakura: ['研究しない！ あたしが誰を見てたとか、ノートに書かない！'],
    heikatsu: ['先生、内進にも戻ります！ ……試合が全部終わったら、です'],
    kakusei: ['……'],
  },
  blockText: '平気だし！',
  koText: '応援、届いた！',
  stats: { power: 2, speed: 5, honshitsu: 1, joushiki: 4 },
  desc: '内進生なのに、体育着と白い鉢巻で理数科の応援席に来た三峰瑠衣。三年最後の球技大会、バスケットボールを応援している。「こっちの方が面白いから」と言い張るが、とりわけ三重のスティールと速攻、冷笑しない全力のプレーを目で追っていた。58対60、二点差の敗戦後は一階へ降りて「あんたのプレー、かっこよかった」。今日は人への恋愛指南より、自分の声の大きさを隠すのに忙しい。',
};
